FROM centos

MAINTAINER TAKATOSHI KONDO redboltz@gmail.com

RUN yum -y install gcc
RUN yum -y install gcc-c++
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool

RUN yum -y install git
RUN yum -y install wget
RUN yum -y install unzip

RUN yum -y install make
RUN yum -y install cmake

RUN yum -y install zlib-devel
RUN yum -y install valgrind

RUN wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
RUN unzip gtest-1.7.0.zip
RUN cd gtest-1.7.0 && cmake . && make
RUN cp -r /gtest-1.7.0/include/gtest /usr/local/include
RUN cp /gtest-1.7.0/*.a /usr/local/lib
